package com.solacecoe.connectors.database.source.entity;
// Generated Jul 27, 2023 5:44:34 PM by Hibernate Tools 5.6.2.Final



import jakarta.persistence.*;
import java.util.Date;

/**
 * HomeAddr generated by hbm2java
 */
@Entity
@Table(name="HOME_ADDR"
        ,schema = "dbo"
)
public class HomeAddr1 implements java.io.Serializable {


     private Integer hno;
     private String name;
     private String address;
     private String city;
     private String state;
     private String zip;

    @Column(name="FLAG", nullable=false)
     public String getFlag() {
        return flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

    private String flag;

    @Column(name="DBTRACKID", nullable=false)
    public String getDbtrackid() {
        return dbtrackid;
    }

    public void setDbtrackid(String dbtrackid) {
        this.dbtrackid = dbtrackid;
    }

    private String dbtrackid;

    @Column(name="READTIME", nullable=false)
    public Date getReadtime() {
        return readtime;
    }

    public void setReadtime(Date readtime) {
        this.readtime = readtime;
    }

    private Date readtime;

    public HomeAddr1() {
    }

	
    public HomeAddr1(Integer hno, String name, String address, String city, String state) {
        this.hno = hno;
        this.name = name;
        this.address = address;
        this.city = city;
        this.state = state;
    }
    public HomeAddr1(Integer hno, String name, String address, String city, String state, String zip) {
       this.hno = hno;
       this.name = name;
       this.address = address;
       this.city = city;
       this.state = state;
       this.zip = zip;

    }
   
     @Id 

    
    @Column(name="HNO", nullable=false)
    public Integer getHno() {
        return this.hno;
    }
    
    public void setHno(Integer hno) {
        this.hno = hno;
    }

    
    @Column(name="NAME", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }


    @Column(name="ADDRESS", nullable=false)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="CITY", nullable=false)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="STATE", nullable=false)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="ZIP")
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }



}


