package com.solacecoe.connectors.database.source.entity;
// Generated Dec 17, 2023, 3:22:23 PM by Hibernate Tools 5.6.2.Final


import java.math.BigDecimal;
import java.util.Date;
import jakarta.persistence.*;

/**
 * HomeAddr generated by hbm2java
 */
@Entity
@Table(name="home_addr"

)
public class HomeAddr  implements java.io.Serializable {


     private BigDecimal hno;
     private String address;
     private String city;
     private String name;
     private String state;
     private String zip;
     private String zone;
     private String dbtrackid;
     private Date readtime;
     private String flag;

    public HomeAddr() {
    }

	
    public HomeAddr(BigDecimal hno) {
        this.hno = hno;
    }
    public HomeAddr(BigDecimal hno, String address, String city, String name, String state, String zip, String zone, String dbtrackid, Date readtime, String flag) {
       this.hno = hno;
       this.address = address;
       this.city = city;
       this.name = name;
       this.state = state;
       this.zip = zip;
       this.zone = zone;
       this.dbtrackid = dbtrackid;
       this.readtime = readtime;
       this.flag = flag;
    }
   
     @Id 

    
    @Column(name="hno", unique=true, nullable=false)
    public BigDecimal getHno() {
        return this.hno;
    }
    
    public void setHno(BigDecimal hno) {
        this.hno = hno;
    }

    
    @Column(name="address")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="city")
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="state")
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="zip")
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }

    
    @Column(name="zone")
    public String getZone() {
        return this.zone;
    }
    
    public void setZone(String zone) {
        this.zone = zone;
    }

    
    @Column(name="dbtrackid", length=50)
    public String getDbtrackid() {
        return this.dbtrackid;
    }
    
    public void setDbtrackid(String dbtrackid) {
        this.dbtrackid = dbtrackid;
    }

    
    @Column(name="readtime", length=23)
    public Date getReadtime() {
        return this.readtime;
    }
    
    public void setReadtime(Date readtime) {
        this.readtime = readtime;
    }

    
    @Column(name="flag", length=10)
    public String getFlag() {
        return this.flag;
    }
    
    public void setFlag(String flag) {
        this.flag = flag;
    }




}


