package com.solacecoe.connectors.database.source.entity;
// Generated Feb 17, 2023 9:03:26 PM by Hibernate Tools 5.6.2.Final


import jakarta.persistence.*;

/**
 * PassAddress generated by hbm2java
 */
@Entity
@Table(name="PASS_ADDRESS1"
)
public class PassAddress1 implements java.io.Serializable {


    private PassAddress1Id id;

    public PassAddress1() {
    }

    public PassAddress1(PassAddress1Id id) {
        this.id = id;
    }

    @EmbeddedId


    @AttributeOverrides( {
            @AttributeOverride(name="id", column=@Column(name="ID", nullable=false, precision=10, scale=0) ),
            @AttributeOverride(name="city", column=@Column(name="CITY") ),
            @AttributeOverride(name="zip", column=@Column(name="ZIP") ),
            @AttributeOverride(name="passId", column=@Column(name="PASS_ID", precision=10, scale=0) ) } )
    public PassAddress1Id getId() {
        return this.id;
    }

    public void setId(PassAddress1Id id) {
        this.id = id;
    }




}


