package com.solacecoe.connectors.database.source.entity;
// Generated Feb 17, 2023 9:03:26 PM by Hibernate Tools 5.6.2.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;

/**
 * SourcePassengerId generated by hbm2java
 */
@Embeddable
public class SourcePassenger1Id implements java.io.Serializable {


    private static final long serialVersionUID = -4340547710844731372L;
    private BigDecimal passengerId;

     private String address;
     private Date birthday;

     private String clobc;
     private BigDecimal contactNo;
     private Date createdAt;
    private String flag;
    @Column(name="FLAG")
    public String getFlag() {
        return this.flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }
     private String name;
     private String nationality;

    public SourcePassenger1Id() {
    }


    public SourcePassenger1Id(BigDecimal passengerId) {
        this.passengerId = passengerId;
    }



    @Column(name="PASSENGER_ID", nullable=false, precision=10, scale=0)
    public BigDecimal getPassengerId() {
        return this.passengerId;
    }
    
    public void setPassengerId(BigDecimal passengerId) {
        this.passengerId = passengerId;
    }




    @Column(name="ADDRESS")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }


    @Column(name="BIRTHDAY", length=11)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }





    @Column(name="CLOBC")
    public String getClobc() {
        return this.clobc;
    }
    
    public void setClobc(String clobc) {
        this.clobc = clobc;
    }


    @Column(name="CONTACT_NO")
    public BigDecimal getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(BigDecimal contactNo) {
        this.contactNo = contactNo;
    }


    @Column(name="CREATED_AT", length=11)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }





    @Column(name="NAME")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }


    @Column(name="NATIONALITY")
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SourcePassenger1Id that = (SourcePassenger1Id) o;
        return Objects.equals(passengerId, that.passengerId) && Objects.equals(address, that.address) && Objects.equals(birthday, that.birthday) && Objects.equals(clobc, that.clobc) && Objects.equals(contactNo, that.contactNo) && Objects.equals(createdAt, that.createdAt) && Objects.equals(flag, that.flag) && Objects.equals(name, that.name) && Objects.equals(nationality, that.nationality);
    }

    @Override
    public int hashCode() {
        return Objects.hash(passengerId, address, birthday, clobc, contactNo, createdAt, flag, name, nationality);
    }
}


