package com.solacecoe.connectors.database.source.entity;
// Generated Dec 20, 2024, 8:47:48 AM by Hibernate Tools 5.6.15.Final


import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;

import jakarta.persistence.Entity;

import java.util.Date;
import java.util.List;
import java.util.Map;

/**
 * SourcePassenger generated by hbm2java
 */
@Entity
@Table(name="SOURCE_PASSENGER"
)
public class SourcePassengerRi implements java.io.Serializable {

    private String dbtrackid;
    private Date readtime;
    private String address;
    private Date birthday;
    private byte[] blobc;
    private String clobc;
    private String contactNo;
    private Date createdAt;
    private String flag;
    private String name;
    private String nationality;
    private SourcePassengerRiId id;

    public SourcePassengerRi() {
    }

    public SourcePassengerRi(SourcePassengerRiId id) {
        this.id = id;
    }

    @Column(name="DBTRACKID")
    public String getDbtrackid() {
        return this.dbtrackid;
    }

    public void setDbtrackid(String dbtrackid) {
        this.dbtrackid = dbtrackid;
    }


    @Column(name="READTIME", length=11)
    public Date getReadtime() {
        return this.readtime;
    }

    public void setReadtime(Date readtime) {
        this.readtime = readtime;
    }


    @Column(name="ADDRESS")
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }


    @Column(name="BIRTHDAY", length=11)
    public Date getBirthday() {
        return this.birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }


    @Column(name="BLOBC")
    public byte[] getBlobc() {
        return this.blobc;
    }

    public void setBlobc(byte[] blobc) {
        this.blobc = blobc;
    }


    @Column(name="CLOBC")
    public String getClobc() {
        return this.clobc;
    }

    public void setClobc(String clobc) {
        this.clobc = clobc;
    }


    @Column(name="CONTACT_NO")
    public String getContactNo() {
        return this.contactNo;
    }

    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }


    @Column(name="CREATED_AT", length=11)
    public Date getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }


    @Column(name="FLAG")
    public String getFlag() {
        return this.flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }


    @Column(name="NAME")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }


    @Column(name="NATIONALITY")
    public String getNationality() {
        return this.nationality;
    }

    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    private List<Map> addresses;

//    @JsonIgnore
    @Transient
    public List<Map> getAddresses() {
        return addresses;
    }
    public void setAddresses(List<Map> addresses) {
        this.addresses = addresses;}

    @EmbeddedId


    @AttributeOverrides( {
            @AttributeOverride(name="passengerId", column=@Column(name="PASSENGER_ID", nullable=false, precision=10, scale=0) )
    } )
    public SourcePassengerRiId getId() {
        return this.id;
    }

    public void setId(SourcePassengerRiId id) {
        this.id = id;
    }




}


