package com.solacecoe.connectors.database.source.entity;
// Generated Dec 20, 2024, 8:47:48 AM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.Embeddable;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Date;
import java.util.Objects;
import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * SourcePassengerId generated by hbm2java
 */
@Embeddable
public class SourcePassengerRiId implements java.io.Serializable {


    private BigDecimal passengerId;


    public SourcePassengerRiId() {
    }


    public SourcePassengerRiId(BigDecimal passengerId) {
        this.passengerId = passengerId;
    }




    @Column(name="PASSENGER_ID", nullable=false, precision=10, scale=0)
    public BigDecimal getPassengerId() {
        return this.passengerId;
    }

    public void setPassengerId(BigDecimal passengerId) {
        this.passengerId = passengerId;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SourcePassengerRiId that = (SourcePassengerRiId) o;
        return Objects.equals(passengerId, that.passengerId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(passengerId);
    }
}


