package com.solacecoe.connectors.database.source.entity;
// Generated Feb 17, 2023 9:03:26 PM by Hibernate Tools 5.6.2.Final


import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.*;
import java.util.Date;
import java.util.List;
import java.util.Map;

/**
 * SourcePassenger generated by hbm2java
 */
@Entity
@Table(name="source_noflag"
)
public class SourcePassenger  implements java.io.Serializable {

    private static final long serialVersionUID = 3303542174308193568L;
    private String dbtrackid;
    private Date readtime;
    @Column(name="DBTRACKID")
    public String getDbtrackid() {
        return this.dbtrackid;
    }

    public void setDbtrackid(String dbtrackid) {
        this.dbtrackid = dbtrackid;
    }

    private byte[] blobc;

    @Column(name="BLOBC")
    public byte[] getBlobc() {
        return this.blobc;
    }

    public void setBlobc(byte[] blobc) {
        this.blobc = blobc;
    }


    @Column(name="READTIME", length=11)
    public Date getReadtime() {
        return this.readtime;
    }

    public void setReadtime(Date readtime) {
        this.readtime = readtime;
    }

    private List<Map> addresses;

    //@JsonIgnore
    @Transient
    public List<Map> getAddresses() {
        return addresses;
    }
    public void setAddresses(List<Map> addresses) {
        this.addresses = addresses;}

    private SourcePassengerId id;

    public SourcePassenger() {
    }

    public SourcePassenger(SourcePassengerId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="passengerId", column=@Column(name="PASSENGER_ID", nullable=false, precision=10, scale=0) ), 

        @AttributeOverride(name="address", column=@Column(name="ADDRESS") ), 
        @AttributeOverride(name="birthday", column=@Column(name="BIRTHDAY", length=11) ), 

        @AttributeOverride(name="clobc", column=@Column(name="CLOBC") ), 
        @AttributeOverride(name="contactNo", column=@Column(name="CONTACT_NO") ), 
        @AttributeOverride(name="createdAt", column=@Column(name="CREATED_AT", length=11) ), 
        @AttributeOverride(name="name", column=@Column(name="NAME") ),
        @AttributeOverride(name="nationality", column=@Column(name="NATIONALITY") ) } )
    public SourcePassengerId getId() {
        return this.id;
    }
    
    public void setId(SourcePassengerId id) {
        this.id = id;
    }



}


