package com.solace.connectors.database.sink.entity;
// Generated Jan 15, 2026, 11:21:07 AM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.math.BigDecimal;
import java.util.Date;

/**
 * TestMetrics generated by hbm2java
 */
@Entity
@Table(name="test_metrics"
    ,schema="public"
)
public class TestMetricsSink implements java.io.Serializable {


     private Integer metricId;
     private Integer testId;
     private String metricName;
     private BigDecimal metricValue;
     private Date recordedAt;

    public TestMetricsSink() {
    }

	
    public TestMetricsSink(Integer metricId, Integer testId, String metricName, BigDecimal metricValue) {
        this.metricId = metricId;
        this.testId = testId;
        this.metricName = metricName;
        this.metricValue = metricValue;
    }
    public TestMetricsSink(Integer metricId, Integer testId, String metricName, BigDecimal metricValue, Date recordedAt) {
       this.metricId = metricId;
       this.testId = testId;
       this.metricName = metricName;
       this.metricValue = metricValue;
       this.recordedAt = recordedAt;
    }
   
     @Id 

    
    @Column(name="metric_id", unique=true, nullable=false)
    public Integer getMetricId() {
        return this.metricId;
    }
    
    public void setMetricId(Integer metricId) {
        this.metricId = metricId;
    }

    
    @Column(name="test_id", nullable=false)
    public Integer getTestId() {
        return this.testId;
    }
    
    public void setTestId(Integer testId) {
        this.testId = testId;
    }

    
    @Column(name="metric_name", nullable=false, length=100)
    public String getMetricName() {
        return this.metricName;
    }
    
    public void setMetricName(String metricName) {
        this.metricName = metricName;
    }

    
    @Column(name="metric_value", nullable=false, precision=10)
    public BigDecimal getMetricValue() {
        return this.metricValue;
    }
    
    public void setMetricValue(BigDecimal metricValue) {
        this.metricValue = metricValue;
    }

    
    @Column(name="recorded_at", length=35)
    public Date getRecordedAt() {
        return this.recordedAt;
    }
    
    public void setRecordedAt(Date recordedAt) {
        this.recordedAt = recordedAt;
    }




}


