package com.solace.connectors.database.sink.entity;
// Generated Jan 15, 2026, 11:21:07 AM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.util.Date;

/**
 * TestIdentification generated by hbm2java
 */
@Entity
@Table(name="test_identification"
    ,schema="public"
)
public class TestIdentificationSink implements java.io.Serializable {


     private Integer testId;
     private String testName;
     private Date createdAt;

    public TestIdentificationSink() {
    }

	
    public TestIdentificationSink(Integer testId, String testName) {
        this.testId = testId;
        this.testName = testName;
    }
    public TestIdentificationSink(Integer testId, String testName, Date createdAt) {
       this.testId = testId;
       this.testName = testName;
       this.createdAt = createdAt;
    }
   
     @Id 

    
    @Column(name="test_id", unique=true, nullable=false)
    public Integer getTestId() {
        return this.testId;
    }
    
    public void setTestId(Integer testId) {
        this.testId = testId;
    }

    
    @Column(name="test_name", nullable=false, length=100)
    public String getTestName() {
        return this.testName;
    }
    
    public void setTestName(String testName) {
        this.testName = testName;
    }

    
    @Column(name="created_at", length=35)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }




}


