package com.solace.connectors.database.source.entity;
// Generated Jan 15, 2026, 8:33:25 AM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.io.Serializable;
import java.util.Date;
import java.math.BigDecimal;

/**
 * TestMetrics generated by hbm2java
 */
@Entity
@Table(name="TEST_METRICS"
    ,schema="TESTUSER"
)
public class TestMetrics  implements java.io.Serializable {


     private BigDecimal metricId;
     private BigDecimal testId;
     private String metricName;
     private BigDecimal metricValue;
     private Date recordedAt;

    public TestMetrics() {
    }

	
    public TestMetrics(BigDecimal metricId, BigDecimal testId, String metricName) {
        this.metricId = metricId;
        this.testId = testId;
        this.metricName = metricName;
    }
    public TestMetrics(BigDecimal metricId, BigDecimal testId, String metricName, BigDecimal metricValue, Date recordedAt) {
       this.metricId = metricId;
       this.testId = testId;
       this.metricName = metricName;
       this.metricValue = metricValue;
       this.recordedAt = recordedAt;
    }
   
     @Id 

    
    @Column(name="METRIC_ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getMetricId() {
        return this.metricId;
    }
    
    public void setMetricId(BigDecimal metricId) {
        this.metricId = metricId;
    }

    
    @Column(name="TEST_ID", nullable=false, precision=22, scale=0)
    public BigDecimal getTestId() {
        return this.testId;
    }
    
    public void setTestId(BigDecimal testId) {
        this.testId = testId;
    }

    
    @Column(name="METRIC_NAME", nullable=false, length=100)
    public String getMetricName() {
        return this.metricName;
    }
    
    public void setMetricName(String metricName) {
        this.metricName = metricName;
    }

    
    @Column(name="METRIC_VALUE", precision=10)
    public BigDecimal getMetricValue() {
        return this.metricValue;
    }
    
    public void setMetricValue(BigDecimal metricValue) {
        this.metricValue = metricValue;
    }

    
    @Column(name="RECORDED_AT", length=11)
    public Date getRecordedAt() {
        return this.recordedAt;
    }
    
    public void setRecordedAt(Date recordedAt) {
        this.recordedAt = recordedAt;
    }




}


