package com.solace.connectors.database.source.entity;
// Generated Jan 15, 2026, 8:33:25 AM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.io.Serializable;
import java.util.Date;
import java.math.BigDecimal;

/**
 * TestIdentification generated by hbm2java
 */
@Entity
@Table(name="TEST_IDENTIFICATION"
    ,schema="TESTUSER"
)
public class TestIdentification  implements java.io.Serializable {


     private BigDecimal id;
     private String testName;
     private Date createdAt;

    public TestIdentification() {
    }

	
    public TestIdentification(BigDecimal id, String testName) {
        this.id = id;
        this.testName = testName;
    }
    public TestIdentification(BigDecimal id, String testName, Date createdAt) {
       this.id = id;
       this.testName = testName;
       this.createdAt = createdAt;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    
    @Column(name="TEST_NAME", nullable=false, length=100)
    public String getTestName() {
        return this.testName;
    }
    
    public void setTestName(String testName) {
        this.testName = testName;
    }

    
    @Column(name="CREATED_AT", length=11)
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }




}


