#!/usr/bin/env bash
set -euo pipefail

# -----------------------------------------------------------------------------
# create-jpa-oracle-source-package.sh
# Creates jpa-oracle-source-package.zip inside ./jpa-oracle-source-package
# -----------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKDIR="${SCRIPT_DIR}"

ROOT_DIR="${WORKDIR}/.."

SRC_ENV="${ROOT_DIR}/sample.env"
SRC_APP_YML="${ROOT_DIR}/jpa-oracle-config/application.yml"
SRC_COMPOSE="${ROOT_DIR}/docker-compose.yml"

OUT_ENV="${WORKDIR}/sample.env"
OUT_APP_YML="${WORKDIR}/application.yml"
OUT_COMPOSE="${WORKDIR}/docker-compose.yml"

ZIP_NAME="jpa-oracle-source-package.zip"
ZIP_PATH="${WORKDIR}/${ZIP_NAME}"

TAG_SERVICES="services"
TAG_JPA="jpa-oracle-source"

# .env tags
ENV_TAGS=("ORACLE" "SOLACE" "DATADOG" "WORKFLOW")

die() { echo "ERROR: $*" >&2; exit 1; }

require_file() {
  local f="$1"
  [[ -f "$f" ]] || die "Missing required file: $f"
}

# Extract lines between BO <tag> and EO <tag> (exclusive).
# Supports both plain and commented markers:
#   BO tag / EO tag
#   # BO tag / #EO tag / #BO tag
extract_tag_block() {
  local file="$1"
  local tag="$2"

  awk -v tag="$tag" '
    BEGIN {
      start = "^[[:space:]]*#?[[:space:]]*BO[[:space:]]+" tag "([[:space:]]*$)"
      end   = "^[[:space:]]*#?[[:space:]]*EO[[:space:]]+" tag "([[:space:]]*$)"
      inblock=0
    }
    $0 ~ start { inblock=1; next }
    $0 ~ end   { inblock=0; next }
    inblock { print }
  ' "$file"
}

ensure_tag_present() {
  local file="$1"
  local tag="$2"

  local bo_re="^[[:space:]]*#?[[:space:]]*BO[[:space:]]+${tag}([[:space:]]*$)"
  local eo_re="^[[:space:]]*#?[[:space:]]*EO[[:space:]]+${tag}([[:space:]]*$)"

  grep -qE "$bo_re" "$file" || die "Missing tag start marker for '${tag}' in ${file}"
  grep -qE "$eo_re" "$file" || die "Missing tag end marker for '${tag}' in ${file}"

  if [[ -z "$(extract_tag_block "$file" "$tag" | sed -e '/^[[:space:]]*$/d')" ]]; then
    die "Tag block '${tag}' in ${file} is empty (or only whitespace)."
  fi
}

main() {
  echo "Workfolder : ${WORKDIR}"
  echo "Repo root  : ${ROOT_DIR}"

  require_file "$SRC_ENV"
  require_file "$SRC_APP_YML"
  require_file "$SRC_COMPOSE"

  # Validate docker-compose.yml tags
  ensure_tag_present "$SRC_COMPOSE" "$TAG_SERVICES"
  ensure_tag_present "$SRC_COMPOSE" "$TAG_JPA"

  # Validate sample.env tags
  for t in "${ENV_TAGS[@]}"; do
    ensure_tag_present "$SRC_ENV" "$t"
  done

  echo "Creating tagged sample.env in workfolder from ${SRC_ENV} ..."
  {
    echo "# Generated by $(basename "$0") on $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    echo "# Source: ${SRC_ENV}"
    echo "# Included tags: ${ENV_TAGS[*]}"
    echo
    for t in "${ENV_TAGS[@]}"; do
      echo "# ---- BEGIN ${t} ----"
      extract_tag_block "$SRC_ENV" "$t"
      echo "# ---- END ${t} ----"
      echo
    done
  } > "$OUT_ENV"

  [[ -s "$OUT_ENV" ]] || die "Failed to generate ${OUT_ENV} (file is empty)."

  echo "Copying ${SRC_APP_YML} -> ${OUT_APP_YML}"
  cp -f "$SRC_APP_YML" "$OUT_APP_YML"

  echo "Creating tagged docker-compose.yml in workfolder from ${SRC_COMPOSE} ..."
  {
    echo "# Generated by $(basename "$0") on $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
    echo "# Source: ${SRC_COMPOSE}"
    echo
    extract_tag_block "$SRC_COMPOSE" "$TAG_SERVICES"
    echo
    extract_tag_block "$SRC_COMPOSE" "$TAG_JPA"
    echo
  } > "$OUT_COMPOSE"

  [[ -s "$OUT_COMPOSE" ]] || die "Failed to generate ${OUT_COMPOSE} (file is empty)."

  echo "Removing existing zip if present: ${ZIP_PATH}"
  rm -f "$ZIP_PATH"

  echo "Zipping workfolder contents -> ${ZIP_PATH}"
  (
    cd "$WORKDIR"
    zip -r "$ZIP_NAME" . \
      -x "./${ZIP_NAME}" \
      -x "./.DS_Store" \
      -x "./__MACOSX/*"
  )

  echo "Done."
  echo "Created: ${ZIP_PATH}"
}

main "$@"
