ALTER SESSION SET CONTAINER = ORCLPDB1;

CREATE USER testuser IDENTIFIED BY Oradoc_db1
  DEFAULT TABLESPACE users
  TEMPORARY TABLESPACE temp
  QUOTA UNLIMITED ON users;

GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE TO testuser;
