package com.solacecoe.connectors.database.sink.entity;
// Generated Feb 11, 2025, 8:53:13 AM by Hibernate Tools 5.6.15.Final


import jakarta.persistence.*;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Passenger generated by hbm2java
 */
@Entity
@Table(name="PASSENGER"
        ,schema = "C##TEST"
)
public class Passenger implements java.io.Serializable {


     private BigDecimal passengerId;
     private String address;
     private byte[] blobc;
     private String clobc;
     private String contactNo;
     private Date day;
     private String name;
     private String nationality;

    public Passenger() {
    }

	
    public Passenger(BigDecimal passengerId) {
        this.passengerId = passengerId;
    }
    public Passenger(BigDecimal passengerId, String address, byte[] blobc, String clobc, String contactNo, Date day, String name, String nationality) {
       this.passengerId = passengerId;
       this.address = address;
       this.blobc = blobc;
       this.clobc = clobc;
       this.contactNo = contactNo;
       this.day = day;
       this.name = name;
       this.nationality = nationality;
    }
   
     @Id 

    
    @Column(name="PASSENGER_ID", unique=true, nullable=false, precision=10, scale=0)
    public BigDecimal getPassengerId() {
        return this.passengerId;
    }
    
    public void setPassengerId(BigDecimal passengerId) {
        this.passengerId = passengerId;
    }

    
    @Column(name="ADDRESS")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="BLOBC")
    public byte[] getBlobc() {
        return this.blobc;
    }
    
    public void setBlobc(byte[] blobc) {
        this.blobc = blobc;
    }

    
    @Column(name="CLOBC")
    public String getClobc() {
        return this.clobc;
    }
    
    public void setClobc(String clobc) {
        this.clobc = clobc;
    }

    
    @Column(name="CONTACT_NO")
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

    
    @Column(name="DAY", length=11)
    public Date getDay() {
        return this.day;
    }
    
    public void setDay(Date day) {
        this.day = day;
    }

    
    @Column(name="NAME")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="NATIONALITY")
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }




}


